version: "2"

services:
  web:
    build: docker_build/develop
    volumes:
     - ../../:/var/www/html/
     - ./dev-scripts/:/root/dev-scripts
    links:
     - db
     - mailcatcher
    environment:
     - VIRTUAL_HOST=wim.dev
     - DRUPAL_SETTINGS=development
    ports:
     - "80"
    network_mode: "bridge"

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wim
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    network_mode: "bridge"

  mailcatcher:
    image: schickling/mailcatcher
    environment:
      - VIRTUAL_HOST=mailcatcher.wim.dev
      - VIRTUAL_PORT=1080
    ports:
      - "1080"
    network_mode: "bridge"

  selenium:
    image: selenium/standalone-firefox-debug:2.48.2
    links:
     - web:web
    ports:
     - "4444"
     - "5900"
    container_name: wim_selenium
    cap_add:
     - NET_ADMIN
     - NET_RAW
    network_mode: "bridge"

  behat:
    build: docker_build/develop
    container_name: wim_behat
    volumes:
     - ../../:/var/www/html/
     - ./dev-scripts/:/root/dev-scripts
     - ./behat/:/root/behat
    links:
     - web:web
     - db:db
     - selenium:selenium
    environment:
     - DRUPAL_SETTINGS=development

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: "bridge"

volumes:
  db_data:
