version: "2"

services:
  web:
    build: docker_build/develop
    volumes:
      - ../../:/var/www/html/
      - ./dev-scripts/:/root/dev-scripts
    links:
      - db
      - mailcatcher
    environment:
      - VIRTUAL_HOST=wim.dev
      - DRUPAL_SETTINGS=development
    ports:
      - "80"

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wim
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"

  mailcatcher:
    image: schickling/mailcatcher
    environment:
      - VIRTUAL_HOST=mailcatcher.wim.dev
      - VIRTUAL_PORT=1080
    ports:
      - "1080"

  selenium:
    image: selenium/standalone-firefox-debug:2.48.2
    ports:
      - "4444"
      - "5900"
    container_name: wim_selenium
    cap_add:
      - NET_ADMIN
      - NET_RAW
    links:
      - web

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  db_data:
